name: ServerPlus
main: tw.momocraft.serverplus.ServerPlus
author: Momocraft
api-version: 1.13
version: 1.0.3
description: Server utils.
softdepend: [Vault, PlayerPoints, PlaceHolderAPI, MythicMobs, CMI, Residence, MyPet, ItemJoin, MorphTool, DiscordSRV, LocaleLib]

commands:
  serverplus:
    description: Displays main command menu.
    permission: serverplus.use
    aliases: [svp]
    usage: |
      /serverplus

permissions:
  serverplus.*:
    description: Allows use of all commands and feature.
    default: op
    children:
      serverplus.use: true
      ServerPlus.command.*: true
      ServerPlus.bypass.*: true
  ServerPlus.use:
    description: Allows use of basic commands.
    default: true
  ServerPlus.command.*:
    description: Allows use all commands.
    default: op
    children:
      ServerPlus.command.reload: true
      ServerPlus.command.version: true
  ServerPlus.command.reload:
    description: Allows use of /ServerPlus command reload.
    default: op
  ServerPlus.command.version:
    description: Allows use of command /ServerPlus version.
    default: op